### ISSUE TITLE
Does not work for long

### ISSUE THREAD

**Issue by ralphlenssen** [mchmx/InputBoxOctober#1]
To force mobile to use the correct keyboard I want to use your widget. However, it only takes string inputs, while I need to add a pattern to a long attribute input.

IMO I think Mendix should default make sure the correct keyboard is shown with number, but sadly they do not.

**Comment by cdcharlebois** [comment]
@ralphlenssen, have you looked at the **Set Attribute** widget on the Mendix App Store? https://appstore.home.mendix.com/link/app/5958/TimeSeries/Set-Attribute 

This should let you set the `type='tel'` on the input box (either a standard one or InputBoxOctober 😉 )

**Comment by ralphlenssen** [comment]
I have indeed found the useful widget. Thanks for the suggestion!
